Env = "dev"

[Admin]
  AuthEnable = true
  HttpListenAddr = "0.0.0.0:49000"

[Logger]
  Addr = []
  Filename = "./log/logger.log"
  Level = -1
  Module = "gin_rbac"

[Mysql]
  ConnMaxLifetime = 7200
  MaxIdleConn = 200
  MaxOpenConn = 50
  ShowSQL = true

  [Mysql.Master]
    Database = "gin_rbac"
    HostPort = "192.168.10.23:3306"
    Password = "111111"
    Username = "root"
